version: '3'

services:
  nginx:
    image: nginx
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - "8076:80"
    depends_on:
      - app
    container_name: project_nginx
  app:
    build:
        context: .
        dockerfile: _docker/app/Dockerfile
    image: php:8.1-fpm
    volumes:
      - ./:/var/www
    container_name: project_app
